name: Reusable Workflow

on:
    workflow_call:
        inputs:
            runner_type:
                description: 'The type of runner to use'
                required: true
                type: string

jobs:
    date:
        runs-on: ${{ inputs.runner_type }}
        steps:
            - name: Echo the date
              run: echo "The date is $(date)"
            - name: Echo the runner OS
              run: echo "The runner OS is $(cat /etc/os-release)"
            - name: Blast the runner label
              run: echo "The runner label is ${{ inputs.runner_label }}"