name: Ubuntu 18 Caller Workflow

on:
    workflow_dispatch:

jobs:
    call_reusable_workflow:
        uses: ./.github/workflows/reusable_workflow.yml
        with:
            runner_type: ubuntu-18
