name: Ubuntu Caller Workflow

on:
    workflow_dispatch:

jobs:
    call_reusable_workflow:
        uses: ./.github/workflows/reusable-workflow.yml@main
        with:
            runner_type: ubuntu-latest
